language: R
cache: packages
sudo: true
dist: trusty

addons:
  apt:
    packages:
      - libfreetype6

r_github_packages:
- tidyverse/ggplot2

matrix:
  include:
  - r: devel
    # avoind errors due to world clock API (hopefully can be removed in future)
    env: _R_CHECK_SYSTEM_CLOCK_=false
  - r: release
  - r: oldrel

# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # switch off vdiffr by default
  - VDIFFR_RUN_TESTS=false

after_success:
  - Rscript -e 'covr::codecov()'

before_install:
  - sudo apt-get --yes --force-yes update -qq
  - Rscript -e 'update.packages(ask = FALSE)'
